CREATE DATABASE customer_behavior;

use customer_behavior;
SELECT * FROM customer LIMIT 10;

SELECT AVG(Purchase_Amount)
FROM Customer_Data;

SELECT AVG(Purchase_Amount) as avg_purchase_amount
FROM Customer;

SELECT Category, COUNT(*) as total
FROM Customer
GROUP BY Category;

SELECT Subscription_Status, COUNT(*) as total
FROM Customer
GROUP BY Subscription_Status;

select* from customer

-- Q1. What is the total revenue generated by male vs. female customers?
select "Gender" ,sum("Purchase_amount")as revenue from customer
group by "Gender";

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select "Customer_ID","Purchase_amount"
from customer
where "Discount_Applied" = 'Yes' and "Purchase_amount"> (select avg("Purchase_amount")from customer)


-- Q3. Which are the top 5 products with the highest average review rating?
select "Item_Purchased",Round(avg("Review_Rating"::numeric),2)
from customer
group by "Item_Purchased"
order by avg("Review_Rating")desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select round(avg("Purchase_amount"),2),"Shipping_Type"
from customer
where "Shipping_Type" in('Express','Standard')
group by "Shipping_Type"

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select "Subscription_Status",
avg("Purchase_amount"),
sum("Purchase_amount")as revenue
from customer
group by "Subscription_Status"
order by revenue

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select "Item_Purchased",
round(100*sum(case when"Discount_Applied"='Yes'then 1 else 0 end)/count(*),2)as discount_rate
from customer
Group by "Item_Purchased"
order by discount_rate desc
limit 5
--Q7. Segment customers into New, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.
with customer_type as(
select "Customer_ID","Previous_Purchases",
case 
when "Previous_Purchases"=1 then 'New'
when "Previous_Purchases" between 2 and 10 then 'Rutrening'
else 'Loyal'
end as customer_segment
from customer
)
select customer_segment ,count(*)as no_of_customer
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
with item_count as (
select "Category","Item_Purchased",
count("Customer_ID")as total_order,
row_number() over (partition by "Category" order by count ("Customer_ID")desc)as item_rank
from customer
group by "Item_Purchased","Category"

)
select "Item_Purchased",item_rank,"Category","total_order"
from item_count
where item_rank<=3
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) 
--also likely to subscribe?
select "Subscription_Status",count("Customer_ID")as repeat_buyers
from customer
where "Previous_Purchases">5
group by "Subscription_Status"

--Q10. What is the revenue contribution of each age group?
select age_group,sum("Purchase_amount")
from customer
group by age_group
